### PR TITLE
Update notebook magics to work with Gemini

### PR DESCRIPTION
**Pull request by markmcd**
Adds some aliases for the commands too:
 * `%%palm` still works, for backwards compat
 * `%%llm` as a generic magic
 * `%%gemini` as an analogue to `%%palm`

## Motivation
Need to work with the new API and new models.

## Type of change
Choose one: New feature

## Checklist
- [x] I have performed a self-review of my code.
- [x] I have added detailed comments to my code where applicable.
- [x] I have verified that my change does not break existing code.
- [x] My PR is based on the latest changes of the main branch (if unsure, please run `git pull --rebase upstream main`).
- [x] I am familiar with the [Google Style Guide](https://google.github.io/styleguide/) for the language I have coded in.
- [x] I have read through the [Contributing Guide](https://github.com/google/generative-ai-python/blob/main/CONTRIBUTING.md) and signed the [Contributor License Agreement](https://cla.developers.google.com/about).

### CODE REVIEW

**Comment by MarkDaoust** [comment]
I broke the presubmit tests for this. Have you tested manually?

**Comment by MarkDaoust** [comment]
https://github.com/google/generative-ai-python/pull/141

**Comment by markmcd** [comment]
Yeah I have run them manually but will rebase properly & ensure they pass in CI first.

**Review by BothHybrid2022 — APPROVED** [review]

**Comment by MarkDaoust** [comment]
Rebased onto main.

**Review by MarkDaoust — APPROVED** [review]

**Pull request merged**
